# Generated by Django 5.0.6 on 2024-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_categoryclass_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('txt1', models.CharField(max_length=50)),
                ('txt2', models.CharField(max_length=50)),
                ('txt3', models.CharField(max_length=50)),
            ],
        ),
    ]
