# Generated by Django 5.0.6 on 2024-11-07 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontentclass',
            name='txt',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
